/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GetCalculatedReservationPrice$Params {
  cpId: number;
  checkin: string;
  checkout: string;
}

export function getCalculatedReservationPrice(http: HttpClient, rootUrl: string, params: GetCalculatedReservationPrice$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
  const rb = new RequestBuilder(rootUrl, getCalculatedReservationPrice.PATH, 'get');
  if (params) {
    rb.path('cpId', params.cpId, {});
    rb.path('checkin', params.checkin, {});
    rb.path('checkout', params.checkout, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: parseFloat(String((r as HttpResponse<any>).body)) }) as StrictHttpResponse<number>;
    })
  );
}

getCalculatedReservationPrice.PATH = '/camperPlace/calcPrice/{cpId}/{checkin}/{checkout}';
