/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CamperPlaceDto } from '../../models/camper-place-dto';

export interface GetCamperPlacesWithUniquePriceAndCamperTypeId$Params {
  typeId: number;
}

export function getCamperPlacesWithUniquePriceAndCamperTypeId(http: HttpClient, rootUrl: string, params: GetCamperPlacesWithUniquePriceAndCamperTypeId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CamperPlaceDto>>> {
  const rb = new RequestBuilder(rootUrl, getCamperPlacesWithUniquePriceAndCamperTypeId.PATH, 'get');
  if (params) {
    rb.path('typeId', params.typeId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CamperPlaceDto>>;
    })
  );
}

getCamperPlacesWithUniquePriceAndCamperTypeId.PATH = '/camperPlace/{typeId}';
