/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GetOccupiedDates$Params {
  cpId: number;
}

export function getOccupiedDates(http: HttpClient, rootUrl: string, params: GetOccupiedDates$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Array<string>>>> {
  const rb = new RequestBuilder(rootUrl, getOccupiedDates.PATH, 'get');
  if (params) {
    rb.path('cpId', params.cpId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Array<string>>>;
    })
  );
}

getOccupiedDates.PATH = '/camperPlace/occupancy/{cpId}';
