/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CountryDistribution } from '../../models/country-distribution';

export interface GetUserPerCountry$Params {
  month: number;
  year: number;
}

export function getUserPerCountry(http: HttpClient, rootUrl: string, params: GetUserPerCountry$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CountryDistribution>>> {
  const rb = new RequestBuilder(rootUrl, getUserPerCountry.PATH, 'get');
  if (params) {
    rb.path('month', params.month, {});
    rb.path('year', params.year, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CountryDistribution>>;
    })
  );
}

getUserPerCountry.PATH = '/statistics/countryDistribution/{month}/{year}';
