/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Revenue } from '../../models/revenue';

export interface GetRevenue$Params {
  month: number;
  year: number;
}

export function getRevenue(http: HttpClient, rootUrl: string, params: GetRevenue$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Array<Revenue>>>> {
  const rb = new RequestBuilder(rootUrl, getRevenue.PATH, 'get');
  if (params) {
    rb.path('month', params.month, {});
    rb.path('year', params.year, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Array<Revenue>>>;
    })
  );
}

getRevenue.PATH = '/statistics/revenue/{month}/{year}';
