/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CamperPlaceTypeDto } from '../../models/camper-place-type-dto';

export interface GetTypes$Params {
}

export function getTypes(http: HttpClient, rootUrl: string, params?: GetTypes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CamperPlaceTypeDto>>> {
  const rb = new RequestBuilder(rootUrl, getTypes.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CamperPlaceTypeDto>>;
    })
  );
}

getTypes.PATH = '/camperPlaceType';
