/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageGuestDto } from '../../models/page-guest-dto';

export interface FindAll1$Params {
  pageable: Pageable;
  by?: string;
  value?: string;
}

export function findAll1(http: HttpClient, rootUrl: string, params: FindAll1$Params, context?: HttpContext): Observable<StrictHttpResponse<PageGuestDto>> {
  const rb = new RequestBuilder(rootUrl, findAll1.PATH, 'get');
  if (params) {
    rb.query('pageable', params.pageable, {});
    rb.query('by', params.by, {});
    rb.query('value', params.value, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageGuestDto>;
    })
  );
}

findAll1.PATH = '/guest';
