/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageGuestDto } from '../../models/page-guest-dto';
import { SearchRequest } from '../../models/search-request';

export interface FindBy1$Params {
      body: SearchRequest
}

export function findBy1(http: HttpClient, rootUrl: string, params: FindBy1$Params, context?: HttpContext): Observable<StrictHttpResponse<PageGuestDto>> {
  const rb = new RequestBuilder(rootUrl, findBy1.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageGuestDto>;
    })
  );
}

findBy1.PATH = '/guest/findBy';
