/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GuestDto } from '../../models/guest-dto';

export interface GetGuestById$Params {
  id: number;
}

export function getGuestById(http: HttpClient, rootUrl: string, params: GetGuestById$Params, context?: HttpContext): Observable<StrictHttpResponse<GuestDto>> {
  const rb = new RequestBuilder(rootUrl, getGuestById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GuestDto>;
    })
  );
}

getGuestById.PATH = '/guest/{id}';
