export interface Country {
  isoCode: string;
  name: string;
}

export const COUNTRIES: Country[] = [
  // Europe
  { isoCode: 'AL', name: 'Albania' },
  { isoCode: 'AD', name: 'Andora' },
  { isoCode: 'AT', name: 'Austria' },
  { isoCode: 'BE', name: 'Belgia' },
  { isoCode: 'BY', name: 'Białoruś' },
  { isoCode: 'BA', name: 'Bośnia i Hercegowina' },
  { isoCode: 'BG', name: 'Bułgaria' },
  { isoCode: 'HR', name: 'Chorwacja' },
  { isoCode: 'CY', name: 'Cypr' },
  { isoCode: 'ME', name: 'Czarnogóra' },
  { isoCode: 'CZ', name: 'Czechy' },
  { isoCode: 'DK', name: 'Dania' },
  { isoCode: 'EE', name: 'Estonia' },
  { isoCode: 'FI', name: 'Finlandia' },
  { isoCode: 'FR', name: 'Francja' },
  { isoCode: 'GR', name: 'Grecja' },
  { isoCode: 'ES', name: 'Hiszpania' },
  { isoCode: 'NL', name: 'Holandia' },
  { isoCode: 'IE', name: 'Irlandia' },
  { isoCode: 'IS', name: 'Islandia' },
  { isoCode: 'LI', name: 'Liechtenstein' },
  { isoCode: 'LT', name: 'Litwa' },
  { isoCode: 'LU', name: 'Luksemburg' },
  { isoCode: 'LV', name: 'Łotwa' },
  { isoCode: 'MK', name: 'Macedonia Północna' },
  { isoCode: 'MT', name: 'Malta' },
  { isoCode: 'MD', name: 'Mołdawia' },
  { isoCode: 'MC', name: 'Monako' },
  { isoCode: 'DE', name: 'Niemcy' },
  { isoCode: 'NO', name: 'Norwegia' },
  { isoCode: 'PL', name: 'Polska' },
  { isoCode: 'PT', name: 'Portugalia' },
  { isoCode: 'RU', name: 'Rosja' },
  { isoCode: 'RO', name: 'Rumunia' },
  { isoCode: 'SM', name: 'San Marino' },
  { isoCode: 'RS', name: 'Serbia' },
  { isoCode: 'SK', name: 'Słowacja' },
  { isoCode: 'SI', name: 'Słowenia' },
  { isoCode: 'CH', name: 'Szwajcaria' },
  { isoCode: 'SE', name: 'Szwecja' },
  { isoCode: 'TR', name: 'Turcja' },
  { isoCode: 'UA', name: 'Ukraina' },
  { isoCode: 'VA', name: 'Watykan' },
  { isoCode: 'HU', name: 'Węgry' },
  { isoCode: 'GB', name: 'Wielka Brytania' },
  { isoCode: 'IT', name: 'Włochy' },

  // Americas
  { isoCode: 'AG', name: 'Antigua i Barbuda' },
  { isoCode: 'AR', name: 'Argentyna' },
  { isoCode: 'BS', name: 'Bahamy' },
  { isoCode: 'BB', name: 'Barbados' },
  { isoCode: 'BZ', name: 'Belize' },
  { isoCode: 'BO', name: 'Boliwia' },
  { isoCode: 'BR', name: 'Brazylia' },
  { isoCode: 'CL', name: 'Chile' },
  { isoCode: 'DO', name: 'Dominikana' },
  { isoCode: 'DM', name: 'Dominika' },
  { isoCode: 'EC', name: 'Ekwador' },
  { isoCode: 'GD', name: 'Grenada' },
  { isoCode: 'GY', name: 'Gujana' },
  { isoCode: 'GT', name: 'Gwatemala' },
  { isoCode: 'HT', name: 'Haiti' },
  { isoCode: 'HN', name: 'Honduras' },
  { isoCode: 'JM', name: 'Jamajka' },
  { isoCode: 'CA', name: 'Kanada' },
  { isoCode: 'CO', name: 'Kolumbia' },
  { isoCode: 'CR', name: 'Kostaryka' },
  { isoCode: 'CU', name: 'Kuba' },
  { isoCode: 'MX', name: 'Meksyk' },
  { isoCode: 'NI', name: 'Nikaragua' },
  { isoCode: 'PA', name: 'Panama' },
  { isoCode: 'PY', name: 'Paragwaj' },
  { isoCode: 'PE', name: 'Peru' },
  { isoCode: 'KN', name: 'Saint Kitts i Nevis' },
  { isoCode: 'LC', name: 'Saint Lucia' },
  { isoCode: 'VC', name: 'Saint Vincent i Grenadyny' },
  { isoCode: 'SV', name: 'Salwador' },
  { isoCode: 'US', name: 'Stany Zjednoczone' },
  { isoCode: 'SR', name: 'Surinam' },
  { isoCode: 'TT', name: 'Trynidad i Tobago' },
  { isoCode: 'UY', name: 'Urugwaj' },
  { isoCode: 'VE', name: 'Wenezuela' },

  // Asia
  { isoCode: 'AF', name: 'Afganistan' },
  { isoCode: 'SA', name: 'Arabia Saudyjska' },
  { isoCode: 'AM', name: 'Armenia' },
  { isoCode: 'AZ', name: 'Azerbejdżan' },
  { isoCode: 'BH', name: 'Bahrajn' },
  { isoCode: 'BD', name: 'Bangladesz' },
  { isoCode: 'BT', name: 'Bhutan' },
  { isoCode: 'MM', name: 'Birma (Mjanma)' },
  { isoCode: 'BN', name: 'Brunei' },
  { isoCode: 'CN', name: 'Chiny' },
  { isoCode: 'PH', name: 'Filipiny' },
  { isoCode: 'GE', name: 'Gruzja' },
  { isoCode: 'IN', name: 'Indie' },
  { isoCode: 'ID', name: 'Indonezja' },
  { isoCode: 'IQ', name: 'Irak' },
  { isoCode: 'IR', name: 'Iran' },
  { isoCode: 'IL', name: 'Izrael' },
  { isoCode: 'JP', name: 'Japonia' },
  { isoCode: 'YE', name: 'Jemen' },
  { isoCode: 'JO', name: 'Jordania' },
  { isoCode: 'KH', name: 'Kambodża' },
  { isoCode: 'QA', name: 'Katar' },
  { isoCode: 'KZ', name: 'Kazachstan' },
  { isoCode: 'KG', name: 'Kirgistan' },
  { isoCode: 'KR', name: 'Korea Południowa' },
  { isoCode: 'KP', name: 'Korea Północna' },
  { isoCode: 'KW', name: 'Kuwejt' },
  { isoCode: 'LA', name: 'Laos' },
  { isoCode: 'LB', name: 'Liban' },
  { isoCode: 'MV', name: 'Malediwy' },
  { isoCode: 'MY', name: 'Malezja' },
  { isoCode: 'MN', name: 'Mongolia' },
  { isoCode: 'NP', name: 'Nepal' },
  { isoCode: 'OM', name: 'Oman' },
  { isoCode: 'PK', name: 'Pakistan' },
  { isoCode: 'PS', name: 'Palestyna' },
  { isoCode: 'SG', name: 'Singapur' },
  { isoCode: 'LK', name: 'Sri Lanka' },
  { isoCode: 'SY', name: 'Syria' },
  { isoCode: 'TJ', name: 'Tadżykistan' },
  { isoCode: 'TH', name: 'Tajlandia' },
  { isoCode: 'TL', name: 'Timor Wschodni' },
  { isoCode: 'TM', name: 'Turkmenistan' },
  { isoCode: 'UZ', name: 'Uzbekistan' },
  { isoCode: 'VN', name: 'Wietnam' },
  { isoCode: 'AE', name: 'Zjednoczone Emiraty Arabskie' },

  // Africa
  { isoCode: 'DZ', name: 'Algieria' },
  { isoCode: 'AO', name: 'Angola' },
  { isoCode: 'BJ', name: 'Benin' },
  { isoCode: 'BW', name: 'Botswana' },
  { isoCode: 'BF', name: 'Burkina Faso' },
  { isoCode: 'BI', name: 'Burundi' },
  { isoCode: 'TD', name: 'Czad' },
  { isoCode: 'CD', name: 'Demokratyczna Republika Konga' },
  { isoCode: 'DJ', name: 'Dżibuti' },
  { isoCode: 'EG', name: 'Egipt' },
  { isoCode: 'ER', name: 'Erytrea' },
  { isoCode: 'SZ', name: 'Eswatini' },
  { isoCode: 'ET', name: 'Etiopia' },
  { isoCode: 'GA', name: 'Gabon' },
  { isoCode: 'GM', name: 'Gambia' },
  { isoCode: 'GH', name: 'Ghana' },
  { isoCode: 'GN', name: 'Gwinea' },
  { isoCode: 'GW', name: 'Gwinea Bissau' },
  { isoCode: 'GQ', name: 'Gwinea Równikowa' },
  { isoCode: 'CM', name: 'Kamerun' },
  { isoCode: 'KE', name: 'Kenia' },
  { isoCode: 'KM', name: 'Komory' },
  { isoCode: 'CG', name: 'Kongo' },
  { isoCode: 'LS', name: 'Lesotho' },
  { isoCode: 'LR', name: 'Liberia' },
  { isoCode: 'LY', name: 'Libia' },
  { isoCode: 'MG', name: 'Madagaskar' },
  { isoCode: 'MW', name: 'Malawi' },
  { isoCode: 'ML', name: 'Mali' },
  { isoCode: 'MA', name: 'Maroko' },
  { isoCode: 'MR', name: 'Mauretania' },
  { isoCode: 'MU', name: 'Mauritius' },
  { isoCode: 'MZ', name: 'Mozambik' },
  { isoCode: 'NA', name: 'Namibia' },
  { isoCode: 'NE', name: 'Niger' },
  { isoCode: 'NG', name: 'Nigeria' },
  { isoCode: 'ZA', name: 'Południowa Afryka' },
  { isoCode: 'CF', name: 'Republika Środkowoafrykańska' },
  { isoCode: 'CV', name: 'Republika Zielonego Przylądka' },
  { isoCode: 'RW', name: 'Rwanda' },
  { isoCode: 'SN', name: 'Senegal' },
  { isoCode: 'SC', name: 'Seszele' },
  { isoCode: 'SL', name: 'Sierra Leone' },
  { isoCode: 'SO', name: 'Somalia' },
  { isoCode: 'SD', name: 'Sudan' },
  { isoCode: 'SS', name: 'Sudan Południowy' },
  { isoCode: 'ST', name: 'Święty Tomasz i Książęca' },
  { isoCode: 'TZ', name: 'Tanzania' },
  { isoCode: 'TG', name: 'Togo' },
  { isoCode: 'TN', name: 'Tunezja' },
  { isoCode: 'UG', name: 'Uganda' },
  { isoCode: 'CI', name: 'Wybrzeże Kości Słoniowej' },
  { isoCode: 'ZM', name: 'Zambia' },
  { isoCode: 'ZW', name: 'Zimbabwe' },

  // Oceania
  { isoCode: 'AU', name: 'Australia' },
  { isoCode: 'FJ', name: 'Fidżi' },
  { isoCode: 'KI', name: 'Kiribati' },
  { isoCode: 'FM', name: 'Mikronezja' },
  { isoCode: 'NR', name: 'Nauru' },
  { isoCode: 'NZ', name: 'Nowa Zelandia' },
  { isoCode: 'PW', name: 'Palau' },
  { isoCode: 'PG', name: 'Papua-Nowa Gwinea' },
  { isoCode: 'WS', name: 'Samoa' },
  { isoCode: 'TO', name: 'Tonga' },
  { isoCode: 'TV', name: 'Tuvalu' },
  { isoCode: 'VU', name: 'Vanuatu' },
  { isoCode: 'MH', name: 'Wyspy Marshalla' },
  { isoCode: 'SB', name: 'Wyspy Salomona' }
];
