export interface Country {
  isoCode: string;
  name: string;
}

export const COUNTRIES: Country[] = [
  // Europe
  { isoCode: 'AL', name: 'Albania' },
  { isoCode: 'AD', name: 'Andora' },
  { isoCode: 'AT', name: 'Austria' },
  { isoCode: 'BE', name: 'Belgia' },
  { isoCode: 'BY', name: 'Białoruś' },
  { isoCode: 'BA', name: 'Bośnia i Hercegowina' },
  { isoCode: 'BG', name: 'Bułgaria' },
  { isoCode: 'HR', name: 'CHORWACJA' },
  { isoCode: 'CY', name: 'Cypr' },
  { isoCode: 'CZ', name: 'Czechy' },
  { isoCode: 'DK', name: 'Dania' },
  { isoCode: 'EE', name: 'Estonia' },
  { isoCode: 'FI', name: 'Finlandia' },
  { isoCode: 'FR', name: 'Francja' },
  { isoCode: 'GR', name: 'Grecja' },
  { isoCode: 'ES', name: 'Hiszpania' },
  { isoCode: 'IE', name: 'Irlandia' },
  { isoCode: 'IS', name: 'Islandia' },
  { isoCode: 'LT', name: 'Litwa' },
  { isoCode: 'LU', name: 'Luksemburg' },
  { isoCode: 'LV', name: 'Łotwa' },
  { isoCode: 'MT', name: 'Malta' },
  { isoCode: 'MD', name: 'Mołdawia' },
  { isoCode: 'MC', name: 'Monako' },
  { isoCode: 'DE', name: 'Niemcy' },
  { isoCode: 'NO', name: 'Norwegia' },
  { isoCode: 'PL', name: 'Polska' },
  { isoCode: 'PT', name: 'Portugalia' },
  { isoCode: 'RO', name: 'Rumunia' },
  { isoCode: 'SM', name: 'San Marino' },
  { isoCode: 'RS', name: 'Serbia' },
  { isoCode: 'SK', name: 'Słowacja' },
  { isoCode: 'SI', name: 'Słowenia' },
  { isoCode: 'CH', name: 'Szwajcaria' },
  { isoCode: 'SE', name: 'Szwecja' },
  { isoCode: 'TR', name: 'Turcja' },
  { isoCode: 'UA', name: 'Ukraina' },
  { isoCode: 'HU', name: 'Węgry' },
  { isoCode: 'GB', name: 'Wielka Brytania' },
  { isoCode: 'IT', name: 'Włochy' },

  //Americas
  { isoCode: 'AG', name: 'Antigua i Barbuda' },
  { isoCode: 'AR', name: 'Argentyna' },
  { isoCode: 'BS', name: 'Bahamy' },
  { isoCode: 'BB', name: 'Barbados' },
  { isoCode: 'BZ', name: 'Belize' },
  { isoCode: 'BO', name: 'Boliwia' },
  { isoCode: 'BR', name: 'Brazylia' },
  { isoCode: 'CL', name: 'Chile' },
  { isoCode: 'CO', name: 'Kolumbia' },
  { isoCode: 'CR', name: 'Kostaryka' },
  { isoCode: 'CU', name: 'Kuba' },
  { isoCode: 'DM', name: 'Dominika' },
  { isoCode: 'DO', name: 'Dominikana' },
  { isoCode: 'EC', name: 'Ekwador' },
  { isoCode: 'SV', name: 'Salwador' },
  { isoCode: 'GD', name: 'Grenada' },
  { isoCode: 'GT', name: 'Gwatemala' },
  { isoCode: 'GY', name: 'Gujana' },
  { isoCode: 'HT', name: 'Haiti' },
  { isoCode: 'HN', name: 'Honduras' },
  { isoCode: 'JM', name: 'Jamajka' },
  { isoCode: 'CA', name: 'Kanada' },
  { isoCode: 'MX', name: 'Meksyk' },
  { isoCode: 'NI', name: 'Nikaragua' },
  { isoCode: 'PA', name: 'Panama' },
  { isoCode: 'PY', name: 'Paragwaj' },
  { isoCode: 'PE', name: 'Peru' },
  { isoCode: 'KN', name: 'Saint Kitts i Nevis' },
  { isoCode: 'LC', name: 'Saint Lucia' },
  { isoCode: 'VC', name: 'Saint Vincent i Grenadyny' },
  { isoCode: 'SR', name: 'Surinam' },
  { isoCode: 'TT', name: 'Trynidad i Tobago' },
  { isoCode: 'US', name: 'Stany Zjednoczone' },
  { isoCode: 'UY', name: 'Urugwaj' },
  { isoCode: 'VE', name: 'Wenezuela' }
];
