/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CamperPlaceDto } from './models/camper-place-dto';
export type { CamperPlaceTypeDto } from './models/camper-place-type-dto';
export type { GuestDto } from './models/guest-dto';
export type { LoginRequest } from './models/login-request';
export type { Pageable } from './models/pageable';
export type { Pageablenull } from './models/pageablenull';
export type { PageGuestDto } from './models/page-guest-dto';
export type { PageReservationDto } from './models/page-reservation-dto';
export type { ReservationDto } from './models/reservation-dto';
export type { Revenue } from './models/revenue';
export type { SearchCriteria } from './models/search-criteria';
export type { Sortnull } from './models/sortnull';
export type { UserDto } from './models/user-dto';
