/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CamperPlaceTypeDto } from '../models/camper-place-type-dto';
export interface CamperPlaceDto {
  id?: number;
  index?: string;
  price: number;
  type: CamperPlaceTypeDto;
}
