/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GuestDto {
  carRegistration?: string;
  country?: string;
  email?: string;
  firstname?: string;
  id?: number;
  lastname?: string;
  phoneNumber?: string;
}
