/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Pageablenull } from '../models/pageablenull';
import { ReservationDto } from '../models/reservation-dto';
import { Sortnull } from '../models/sortnull';
export interface PageReservationDto {
  content?: Array<ReservationDto>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: Pageablenull;
  size?: number;
  sort?: Sortnull;
  totalElements?: number;
  totalPages?: number;
}
