/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CamperPlaceDto } from '../models/camper-place-dto';
import { Pageablenull } from '../models/pageablenull';
import { Sortnull } from '../models/sortnull';
export interface PageCamperPlaceDto {
  content?: Array<CamperPlaceDto>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: Pageablenull;
  size?: number;
  sort?: Sortnull;
  totalElements?: number;
  totalPages?: number;
}
