/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GuestDto } from '../models/guest-dto';
import { Pageablenull } from '../models/pageablenull';
import { Sortnull } from '../models/sortnull';
export interface PageGuestDto {
  content?: Array<GuestDto>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: Pageablenull;
  size?: number;
  sort?: Sortnull;
  totalElements?: number;
  totalPages?: number;
}
