/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReservationMetadataDto {
  checkin?: Array<string>;
  checkout?: Array<string>;
  reserved?: Array<string>;
}
