/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CamperPlaceDto } from '../models/camper-place-dto';
import { GuestDto } from '../models/guest-dto';
export interface ReservationDto {
  camperPlace: CamperPlaceDto;
  checkin: string;
  checkout: string;
  guest: GuestDto;
  id?: number;
  paid: boolean;
  reservationStatus?: string;
}
