/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CamperPlaceDto } from '../models/camper-place-dto';
import { GuestDto } from '../models/guest-dto';
import { UserDto } from '../models/user-dto';
export interface ReservationDto {
  camperPlace: CamperPlaceDto;
  checkin: string;
  checkout: string;
  creator?: UserDto;
  guest: GuestDto;
  id?: number;
  paid: boolean;
  reservationStatus?: 'EXPIRED' | 'ACTIVE' | 'COMING' | 'UNVERIFIED' | 'VERIFIED';
}
