/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SearchCriteria } from '../models/search-criteria';
export interface SearchRequest {
  searchCriteria?: Array<SearchCriteria>;
}
