/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SearchCriteria {
  key?: string;
  operation?: 'EQUALS' | 'NOT_EQUALS' | 'LESS_THEN' | 'GREATER_THEN' | 'BETWEEN' | 'LIKE';
  secondValue?: string;
  value?: string;
}
