/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReservationDto } from '../../models/reservation-dto';

export interface CreateUnverifiedReservationAndSendAuthenticationEmail$Params {
  'X-org-id': any;
  'X-api-key': any;
      body: ReservationDto
}

export function createUnverifiedReservationAndSendAuthenticationEmail(http: HttpClient, rootUrl: string, params: CreateUnverifiedReservationAndSendAuthenticationEmail$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, createUnverifiedReservationAndSendAuthenticationEmail.PATH, 'post');
  if (params) {
    rb.header('X-org-id', params['X-org-id'], {});
    rb.header('X-api-key', params['X-api-key'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

createUnverifiedReservationAndSendAuthenticationEmail.PATH = '/web/reservation/init';
