/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface VerifyReservation$Params {
  targetId: string;
  'X-org-id': any;
  'X-api-key': any;
}

export function verifyReservation(http: HttpClient, rootUrl: string, params: VerifyReservation$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, verifyReservation.PATH, 'post');
  if (params) {
    rb.path('targetId', params.targetId, {});
    rb.header('X-org-id', params['X-org-id'], {});
    rb.header('X-api-key', params['X-api-key'], {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

verifyReservation.PATH = '/web/reservation/verify/{targetId}';
