/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageReservationDto } from '../../models/page-reservation-dto';
import { SearchCriteria } from '../../models/search-criteria';

export interface FindBy$Params {
  pageable: Pageable;
  searchCriteria: SearchCriteria;
}

export function findBy(http: HttpClient, rootUrl: string, params: FindBy$Params, context?: HttpContext): Observable<StrictHttpResponse<PageReservationDto>> {
  const rb = new RequestBuilder(rootUrl, findBy.PATH, 'get');
  if (params) {
    rb.query('pageable', params.pageable, {});
    rb.query('searchCriteria', params.searchCriteria, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageReservationDto>;
    })
  );
}

findBy.PATH = '/reservation';
