/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReservationMetadataDto } from '../../models/reservation-metadata-dto';

export interface GetReservationMetadata$Params {
}

export function getReservationMetadata(http: HttpClient, rootUrl: string, params?: GetReservationMetadata$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: ReservationMetadataDto;
}>> {
  const rb = new RequestBuilder(rootUrl, getReservationMetadata.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      [key: string]: ReservationMetadataDto;
      }>;
    })
  );
}

getReservationMetadata.PATH = '/reservation/getReservationMetadata';
