/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GetUserPerReservation1$Params {
}

export function getUserPerReservation1(http: HttpClient, rootUrl: string, params?: GetUserPerReservation1$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: {
[key: string]: Array<string>;
};
}>> {
  const rb = new RequestBuilder(rootUrl, getUserPerReservation1.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      [key: string]: {
      [key: string]: Array<string>;
      };
      }>;
    })
  );
}

getUserPerReservation1.PATH = '/reservation/getUserPerReservation';
