/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReservationDto } from '../../models/reservation-dto';

export interface GetUserPerReservation$Params {
  date: string;
  camperPlaceId: number;
}

export function getUserPerReservation(http: HttpClient, rootUrl: string, params: GetUserPerReservation$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ReservationDto>>> {
  const rb = new RequestBuilder(rootUrl, getUserPerReservation.PATH, 'get');
  if (params) {
    rb.path('date', params.date, {});
    rb.path('camperPlaceId', params.camperPlaceId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ReservationDto>>;
    })
  );
}

getUserPerReservation.PATH = '/reservation/{date}/{camperPlaceId}';
