/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaidReservationsDto } from '../../models/paid-reservations-dto';

export interface GetPaidReservations$Params {
}

export function getPaidReservations(http: HttpClient, rootUrl: string, params?: GetPaidReservations$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: PaidReservationsDto;
}>> {
  const rb = new RequestBuilder(rootUrl, getPaidReservations.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      [key: string]: PaidReservationsDto;
      }>;
    })
  );
}

getPaidReservations.PATH = '/reservation/getPaidReservations';
